<a href="https://colab.research.google.com/github/q4quang/AIO-2024/blob/feature/Mod8_W1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def predict(X, theta):
    return sigmoid(np.dot(X, theta))

def compute_loss(y_hat, y):
    y_hat = np.clip(y_hat, 1e-7, 1-1e-7)
    return -np.mean(y * np.log(y_hat) + (1 - y) * np.log(1 - y_hat))

def compute_gradient(X, y, y_hat):
    return np.dot(X.T, y_hat - y) / y.size

def update_theta(theta, gradient, lr):
    return theta - lr * gradient

def compute_accuracy(X, y, theta):
    y_hat = predict(X, theta).round()
    return (y_hat == y).mean()

In [3]:
X = [[22.3, -1.5, 1.1, 1]]
theta = [0.1, -0.15, 0.3, -0.2]
predict(X, theta)

array([0.92988994])

In [5]:
y = np.array([1, 0, 0, 1])
y_hat = np.array([0.8, 0.75, 0.3, 0.95])
compute_loss(y_hat, y).round(3)

0.504

In [6]:
X = np.array([[1, 2], [2, 1], [1, 1], [2, 2]])
y = np.array([0, 1, 0, 1])
y_hat = np.array([0.25, 0.75, 0.4, 0.8])
compute_gradient(X, y, y_hat)

array([-0.0625,  0.0625])

In [7]:
y = [1, 0, 1, 1]
y_hat = [0.85, 0.35, 0.9, 0.75]

def compute_accuracy(y, y_hat):
    return np.mean(np.round(y_hat) == y)

compute_accuracy(y, y_hat)

1.0

In [8]:
X = np.array([[1, 3], [2, 1], [3, 2], [1, 2]])
y = np.array([1, 0, 1, 1])
y_hat = np.array([0.7, 0.4, 0.6, 0.85])
compute_gradient(X, y, y_hat)

array([-0.2125, -0.4   ])