<a href="https://colab.research.google.com/github/q4quang/AIO-2024/blob/feature/Module_01_Week_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**I. Câu hỏi tự luận**

**Câu 1**

In [3]:
import torch
import torch.nn as nn


class Softmax(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        x_exp = torch.exp(x)
        sum_exp = x_exp.sum(0, keepdim=True)
        return x_exp/sum_exp


class SoftmaxStable(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        x_max = torch.max(x, dim=0, keepdim=True)
        x_exp = torch.exp(x - x_max.values)
        sum_exp = x_exp.sum(0, keepdim=True)
        return x_exp/sum_exp


data = torch.Tensor([1, 2, 3])
softmax = Softmax()
output1 = softmax(data)
print(output1)

data = torch.Tensor([1, 2, 3])
softmax_stable = SoftmaxStable()
output2 = softmax_stable(data)
print(output2)

tensor([0.0900, 0.2447, 0.6652])
tensor([0.0900, 0.2447, 0.6652])


**Câu 2**

In [23]:
from abc import ABC , abstractmethod

class Ward:
    def __init__(self, name):
        self.name = name
        self.people = []

    def add_person(self, person):
        self.people.append(person)

    def describe(self):
        print(f"Ward name: {self.name}")
        for person in self.people:
            person.describe()

    def count_doctor(self):
        count = 0
        for person in self.people:
            if isinstance(person, Doctor):
                count += 1
        return count

    def sort_age(self):
        self.people.sort(key=lambda x: x._yob, reverse=True)

    def compute_average(self):
        average_yob = 0
        count_teacher = 0
        for person in self.people:
            if isinstance(person, Teacher):
                count_teacher += 1
                average_yob += person._yob
        return average_yob/count_teacher

class Person:
    def __init__(self, name: str, yob: int):
        self._name = name
        self._yob = yob

    def get_yob(self):
        return self._yob

    @abstractmethod
    def describe(self):
        pass

class Student(Person):
    def __init__(self, name: str, yob: int, grade: str):
        super().__init__(name, yob)
        self.grade = grade

    def describe(self):
        print(f"Student - Name: {self._name} - YoB: {self._yob} - Grade: {self.grade}")


class Teacher(Person):
    def __init__(self, name: str, yob: int, subject: str):
        super().__init__(name, yob)
        self.subject = subject

    def describe(self):
        print(
            f"Teacher - Name: {self._name} - YoB: {self._yob} - Subject: {self.subject}")


class Doctor(Person):
    def __init__(self, name: str, yob: int, specialist: str):
        super().__init__(name, yob)
        self.specialist = specialist

    def describe(self):
        print(f"Doctor - Name: {self._name} - YoB: {self._yob} - Specialist: {self.specialist}")


# 2(a)
student1 = Student(name="studentA", yob=2010, grade="7")
student1.describe()
teacher1 = Teacher(name="teacherA", yob=1969, subject="Math")
teacher1.describe()
doctor1 = Doctor(name="doctorA", yob=1945, specialist="Endocrinologists")
doctor1.describe()

# 2(b)
print()
teacher2 = Teacher(name="teacherB", yob=1995, subject="History")
doctor2 = Doctor(name="doctorB", yob=1975, specialist="Cardiologists")
ward1 = Ward(name="ward1")
ward1.add_person(student1)
ward1.add_person(teacher1)
ward1.add_person(teacher2)
ward1.add_person(doctor1)
ward1.add_person(doctor2)
ward1.describe()

# 2(c)
print(f"\nNumber of doctors: {ward1.count_doctor()}")

# 2(d)
print("\nAfter sorting Age of Ward1 people:")
ward1.sort_age()
ward1.describe()

# 2(e)
print(f"\nAverage year of birth (teachers): {ward1.compute_average()}")


Student - Name: studentA - YoB: 2010 - Grade: 7
Teacher - Name: teacherA - YoB: 1969 - Subject: Math
Doctor - Name: doctorA - YoB: 1945 - Specialist: Endocrinologists

Ward name: ward1
Student - Name: studentA - YoB: 2010 - Grade: 7
Teacher - Name: teacherA - YoB: 1969 - Subject: Math
Teacher - Name: teacherB - YoB: 1995 - Subject: History
Doctor - Name: doctorA - YoB: 1945 - Specialist: Endocrinologists
Doctor - Name: doctorB - YoB: 1975 - Specialist: Cardiologists

Number of doctors: 2

After sorting Age of Ward1 people:
Ward name: ward1
Student - Name: studentA - YoB: 2010 - Grade: 7
Teacher - Name: teacherB - YoB: 1995 - Subject: History
Doctor - Name: doctorB - YoB: 1975 - Specialist: Cardiologists
Teacher - Name: teacherA - YoB: 1969 - Subject: Math
Doctor - Name: doctorA - YoB: 1945 - Specialist: Endocrinologists

Average year of birth (teachers): 1982.0


**Câu 3**

In [7]:

class MyStack:
    def __init__(self, capacity):
        self.capacity = capacity
        self.items = []

    def is_empty(self):
        return len(self.items) == 0

    def is_full(self):
        return len(self.items) == self.capacity

    def pop(self):
        if self.is_empty():
            return "Stack is empty."
        return self.items.pop()

    def push(self, value):
        if self.is_full():
            return "Stack is full."
        self.items.append(value)

    def top(self):
        if self.is_empty():
            raise IndexError("Stack is empty.")
        return self.items[-1]


stack1 = MyStack(capacity=5)
print(stack1.is_empty())
stack1.push(1)
stack1.push(2)
print(stack1.is_full())
print(stack1.top())
print(stack1.pop())
print(stack1.top())
print(stack1.pop())
print(stack1.is_empty())


True
False
2
2
1
1
True


**Câu 4**

In [8]:
class MyQueue:
    def __init__(self, capacity):
        self.capacity = capacity
        self.items = []

    def is_empty(self):
        return len(self.items) == 0

    def is_full(self):
        return len(self.items) == self.capacity

    def dequeue(self):
        if self.is_empty():
            return "Queue is empty."
        return self.items.pop(0)

    def enqueue(self, value):
        if self.is_full():
            return "Queue is full."
        self.items.append(value)

    def front(self):
        return self.items[0]


queue1 = MyQueue(capacity=5)
queue1.enqueue(1)
queue1.enqueue(2)
print(queue1.is_full())
print(queue1.front())
print(queue1.dequeue())
print(queue1.front())
print(queue1.dequeue())
print(queue1.is_empty())

False
1
1
2
2
True


**II. Câu hỏi trắc nghiệm**

**Câu 1**

In [9]:
data = torch.Tensor([1, 2, 3])
softmax_function = nn.Softmax(dim=0)
output = softmax_function(data)
assert round(output[0].item(), 2) == 0.09
print(output)

tensor([0.0900, 0.2447, 0.6652])


**Câu 2**

In [10]:
data = torch.Tensor([5, 2, 4])
my_softmax = Softmax()
output = my_softmax(data)
assert round(output[-1].item(), 2) == 0.26
print(output)

tensor([0.7054, 0.0351, 0.2595])


**Câu 3**

In [11]:
data = torch.Tensor([1, 2, 300000000])
my_softmax = Softmax()
output = my_softmax(data)
assert round(output[0].item(), 2) == 0.0
print(output)

tensor([0., 0., nan])


**Câu 4**

In [12]:
data = torch.Tensor([1, 2, 3])
softmax_stable = SoftmaxStable()
output = softmax_stable(data)
assert round(output[-1].item(), 2) == 0.67
print(output)

tensor([0.0900, 0.2447, 0.6652])


**Câu 5**

In [19]:
student1 = Student(name="studentZ2023", yob=2011, grade="6")
assert student1._yob == 2011
student1.describe()

Student - Name: studentZ2023 - YoB: 2011 - Grade: 6


**Câu 6**

In [20]:
teacher1 = Teacher(name="teacherZ2023", yob=1991, subject="History")
assert teacher1._yob == 1991
teacher1.describe()

Teacher - Name: teacherZ2023 - YoB: 1991 - Subject: History


**Câu 7**

In [21]:
doctor1 = Doctor(name="doctorZ2023", yob=1981, specialist="Endocrinologists")
assert doctor1._yob == 1981
doctor1.describe()

Doctor - Name: doctorZ2023 - YoB: 1981 - Specialist: Endocrinologists


**Câu 8**

In [25]:
ward1 = Ward(name="Ward1")
student1 = Student(name="studentA", yob=2010, grade="7")
teacher1 = Teacher(name="teacherA", yob=1969, subject="Math")
teacher2 = Teacher(name="teacherB", yob=1995, subject="History")
doctor1 = Doctor(name="doctorA", yob=1945, specialist="Endocrinologists")
doctor2 = Doctor(name="doctorB", yob=1975, specialist="Cardiologists")
ward1.add_person(student1)
ward1.add_person(teacher1)
ward1.add_person(teacher2)
ward1.add_person(doctor1)
assert ward1.count_doctor() == 1
ward1.add_person(doctor2)
ward1.count_doctor()

2

**Câu 9**

In [26]:
stack1 = MyStack(capacity=5)
stack1.push(1)
assert stack1.is_full() == False
stack1.push(2)
print(stack1.is_full())

False


**Câu 10**

In [27]:
stack1 = MyStack(capacity=5)
stack1.push(1)
assert stack1.is_full() == False
stack1.push(2)
print(stack1.top())

2


**Câu 11**

In [28]:
queue1 = MyQueue(capacity=5)
queue1.enqueue(1)
assert queue1.is_full() == False
queue1.enqueue(2)
print(queue1.is_full())

False


**Câu 12**

In [29]:
queue1 = MyQueue(capacity=5)
queue1.enqueue(1)
assert queue1.is_full() == False
queue1.enqueue(2)
print(queue1.front())

1
